
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadorLexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int VARIOUS = 16;
  public static final int LONG = 4;
  public static final int READ = 8;
  public static final int CHMOD = 24;
  public static final int LS = 3;
  public static final int CP = 15;
  public static final int SLASH = 20;
  public static final int ALL = 17;
  public static final int RM = 18;
  public static final int CD = 9;
  public static final int MV = 14;
  public static final int ID = 23;
  public static final int WRITE = 7;
  public static final int MKDIR = 13;
  public static final int SPACE = 25;
  public static final int PWD = 2;
  public static final int EOF = 0;
  public static final int ACTUAL = 11;
  public static final int error = 1;
  public static final int RMDIR = 19;
  public static final int HIDDEN = 5;
  public static final int AGREGAR = 21;
  public static final int TOUCH = 12;
  public static final int QUITAR = 22;
  public static final int EXECUTE = 6;
  public static final int BACK = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PWD",
  "LS",
  "LONG",
  "HIDDEN",
  "EXECUTE",
  "WRITE",
  "READ",
  "CD",
  "BACK",
  "ACTUAL",
  "TOUCH",
  "MKDIR",
  "MV",
  "CP",
  "VARIOUS",
  "ALL",
  "RM",
  "RMDIR",
  "SLASH",
  "AGREGAR",
  "QUITAR",
  "ID",
  "CHMOD",
  "SPACE"
  };
}

