
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadorLexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AGREGAR = 14;
  public static final int SLASH = 13;
  public static final int TOUCH = 7;
  public static final int LONG = 4;
  public static final int MOVE = 9;
  public static final int HIDDEN = 5;
  public static final int MAKE_DIR = 8;
  public static final int EOF = 0;
  public static final int CHANGE_DIRECTORY = 6;
  public static final int QUITAR = 15;
  public static final int REMOVE_FILE = 11;
  public static final int ID = 16;
  public static final int error = 1;
  public static final int CONTENTS_DIRECTORY = 3;
  public static final int REMOVE_DIR = 12;
  public static final int CURRENT_DIRECTORY = 2;
  public static final int COPY = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CURRENT_DIRECTORY",
  "CONTENTS_DIRECTORY",
  "LONG",
  "HIDDEN",
  "CHANGE_DIRECTORY",
  "TOUCH",
  "MAKE_DIR",
  "MOVE",
  "COPY",
  "REMOVE_FILE",
  "REMOVE_DIR",
  "SLASH",
  "AGREGAR",
  "QUITAR",
  "ID"
  };
}

